### ISSUE TITLE
can you help me?

### ISSUE THREAD

**Issue by vipdn02** [b12f/latenight.blue#2]
i have run "npm start "
but error, can you help me to install this code, please
```

> latenight.blue@0.0.0 start
> node ./bin/www

Info:  Setting up vhost localhost
node:fs:2346
    return binding.writeFileUtf8(
                   ^

Error: ENOENT: no such file or directory, open 'I:\latenight.blue\data\latenight.blue.json'
    at Object.writeFileSync (node:fs:2346:20)
    at Object.fileSyncRead [as read] (I:\latenight.blue\node_modules\lowdb\lib\storages\file-sync.js:24:10)
    at db.read (I:\latenight.blue\node_modules\lowdb\lib\common.js:25:24)
    at Object.init (I:\latenight.blue\node_modules\lowdb\lib\common.js:55:13)
    at module.exports (I:\latenight.blue\node_modules\lowdb\lib\main.js:25:17)
    at module.exports (I:\latenight.blue\src\db.js:5:16)
    at module.exports (I:\latenight.blue\src\routes.js:13:34)
    at module.exports (I:\latenight.blue\src\app.js:12:42)
    at Object.<anonymous> (I:\latenight.blue\bin\www:38:38)
    at Module._compile (node:internal/modules/cjs/loader:1358:14) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'I:\\latenight.blue\\data\\latenight.blue.json'
}

Node.js v20.14.0
```

**Comment by b12f** [comment]
Hello, this repository is *very* old, and I think it's going to be a bit of a pain in the ass to get it running. The newer version has a separate frontend and backend (`lnb-server` and `lnb-client`), you might have more luck with that.

At some point I might just rewrite it back to a git-only decapcms style thing. I think I made the project too complex at some point.
